name: tagged
on:
  workflow_dispatch:
    inputs:
      sanity:
        description: Run the tests tagged "@sanity"
        required: false
        type: boolean
jobs:
  tagged:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # unfortunately, because GitHub Actions expressions
      # are limited, I could not come up with a better way
      # to map boolean values to the tag strings

      # https://github.com/cypress-io/github-action
      - name: Run sanity tests
        if: ${{ github.event.inputs.sanity }}
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          env: grepTags=@sanity
