name: trigger-circleci
on:
  workflow_dispatch:
    inputs:
      # these inputs will be shown to the user on GitHub Actions page
      # and the user can simply check off the tags to run
      sanity:
        description: Run the tests tagged "@sanity"
        required: false
        type: boolean
      regression:
        description: Run the tests tagged "@regression"
        required: false
        type: boolean
      adding:
        description: Run the tests tagged "@adding"
        required: false
        type: boolean
      complete:
        description: Run the tests tagged "@complete"
        required: false
        type: boolean
      editing:
        description: Run the tests tagged "@editing"
        required: false
        type: boolean
      item:
        description: Run the tests tagged "@item"
        required: false
        type: boolean
      persistence:
        description: Run the tests tagged "@persistence"
        required: false
        type: boolean
      routing:
        description: Run the tests tagged "@routing"
        required: false
        type: boolean
      machines:
        description: Number of machines to use
        required: false
        type: integer
        default: 1

jobs:
  trigger-circleci:
    runs-on: ubuntu-20.04
    steps:
      - name: Print GitHub event inputs
        env:
          EVENT: ${{ toJson(github.event.inputs) }}
        run: |
          echo "$EVENT"
          # all environment variables that start with GITHUB_
          # https://github.com/bahmutov/print-env
          npx @bahmutov/print-env GITHUB_

      - name: Trigger CircleCI run
        env:
          CIRCLE_CI_API_TOKEN: ${{ secrets.CIRCLE_CI_API_TOKEN }}
        run: |
          # collect all input parameters into one string
          TAGS=
          if [[ "${{ github.event.inputs.sanity }}" == "true" ]]; then
            TAGS="@sanity"
          fi
          if [[ "${{ github.event.inputs.regression }}" == "true" ]]; then
            TAGS="$TAGS @regression"
          fi
          if [[ "${{ github.event.inputs.adding }}" == "true" ]]; then
            TAGS="$TAGS @adding"
          fi
          if [[ "${{ github.event.inputs.complete }}" == "true" ]]; then
            TAGS="$TAGS @complete"
          fi
          if [[ "${{ github.event.inputs.editing }}" == "true" ]]; then
            TAGS="$TAGS @editing"
          fi
          if [[ "${{ github.event.inputs.item }}" == "true" ]]; then
            TAGS="$TAGS @item"
          fi
          if [[ "${{ github.event.inputs.persistence }}" == "true" ]]; then
            TAGS="$TAGS @persistence"
          fi
          if [[ "${{ github.event.inputs.routing }}" == "true" ]]; then
            TAGS="$TAGS @routing"
          fi

          echo "Collected tags: $TAGS"
          echo "Number of machines: ${{ github.event.inputs.machines }}"

          # https://github.com/bahmutov/trigger-circleci-pipeline
          npx trigger-circleci-pipeline \
            --org bahmutov --project test-todomvc-using-app-actions \
            --branch $GITHUB_REF_NAME \
            --parameters GREP_TAGS="$TAGS",MACHINES=${{ github.event.inputs.machines }}
